import { School, Announcement, SchoolEvent, StudentIdea, SchoolMember } from '@/types';

export const INITIAL_MOCK_SCHOOL: School = {
  id: 'sch-1ο-gel-athens',
  name: '1ο Γενικό Λύκειο Αθηνών (Γεννάδειο)',
  slug: '1o-gel-athens',
  logo_url: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=300&auto=format&fit=crop&q=80',
  cover_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1200&auto=format&fit=crop&q=80',
  description: 'Το επίσημο ψηφιακό κανάλι του 15μελούς Μαθητικού Συμβουλίου του 1ου ΓΕΛ Αθηνών. Ενημερώσεις, εκδηλώσεις & φωνή των μαθητών.',
  theme_color: '#2563eb',
  contact_email: '15meles@1gel-ath.edu.gr',
  contact_phone: '210 321 4567',
  invite_code: '15GL',
  created_by_uid: 'uid-admin-president',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const INITIAL_MOCK_MEMBERS: SchoolMember[] = [
  {
    id: 'mem-1',
    school_id: 'sch-1ο-gel-athens',
    user_uid: 'uid-admin-president',
    email: 'president@1gel.gr',
    full_name: 'Αλέξανδρος Παπαδόπουλος (Πρόεδρος 15μελούς)',
    role: 'admin',
    joined_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'mem-2',
    school_id: 'sch-1ο-gel-athens',
    user_uid: 'uid-student-demo',
    email: 'student@1gel.gr',
    full_name: 'Μαρία Γεωργίου',
    role: 'student',
    joined_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'mem-3',
    school_id: 'sch-1ο-gel-athens',
    user_uid: 'uid-student-nikos',
    email: 'nikos@1gel.gr',
    full_name: 'Νίκος Δημητρίου',
    role: 'student',
    joined_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    school_id: 'sch-1ο-gel-athens',
    title: '📢 Πρόγραμμα Σχολικής Εκδρομής 3ήμερης Γ΄ Λυκείου',
    content: 'Το 15μελές σε συνεργασία με τον Σύλλογο Διδασκόντων ανακοινώνει τους προορισμούς και το πρόγραμμα για την 3ήμερη εκδρομή της Γ΄ Λυκείου. Παρακαλούνται οι μαθητές να προσκομίσουν τις υπεύθυνες δηλώσεις μέχρι την Παρασκευή.',
    category: 'Εκδρομές',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    is_pinned: true,
    author_name: '15μελές Συμβούλιο',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'ann-2',
    school_id: 'sch-1ο-gel-athens',
    title: '🏀 Έναρξη Εσωτερικού Πρωταθλήματος Μπάσκετ & Βόλεϊ',
    content: 'Ξεκινούν οι εγγραφές για τα τμήματα του σχολικού πρωταθλήματος! Δήλωσε την ομάδα του τμήματός σου στο διάλειμμα στον γυμναστή ή ηλεκτρονικά μέσω της πλατφόρμας.',
    category: 'Αθλητισμός',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80',
    is_pinned: false,
    author_name: 'Αθλητική Επιτροπή 15μελούς',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'ann-3',
    school_id: 'sch-1ο-gel-athens',
    title: '🌱 Εθελοντική Δενδροφύτευση & Καθαρισμός Αυλής',
    content: 'Αυτό το Σάββατο στις 10:00 π.μ. ομορφαίνουμε το σχολείο μας! Θα φυτέψουμε λουλούδια και θα βάψουμε τα παγκάκια της αυλής. Θα δοθούν βεβαιώσεις εθελοντισμού.',
    category: 'Θέματα Σχολείου',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
    is_pinned: false,
    author_name: 'Περιβαλλοντική Ομάδα',
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_EVENTS: SchoolEvent[] = [
  {
    id: 'evt-1',
    school_id: 'sch-1ο-gel-athens',
    title: '🎭 Χριστουγεννιάτικη Θεατρική Παράσταση & Bazaar',
    description: 'Η θεατρική ομάδα του σχολείου μας παρουσιάζει την ετήσια παράσταση. Τα έσοδα του bazaar θα διατεθούν στο Χαμόγελο του Παιδιού.',
    event_date: new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0],
    event_time: '18:30',
    location: 'Αίθουσα Εκδηλώσεων Σχολείου',
    cover_image_url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    external_link: 'https://1gel-ath.edu.gr/event-details',
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'evt-2',
    school_id: 'sch-1ο-gel-athens',
    title: '🎓 Ημέρα Επαγγελματικού Προσανατολισμού',
    description: 'Εκπρόσωποι από ελληνικά πανεπιστήμια και επαγγελματίες απαντούν σε ερωτήσεις μαθητών Β\' και Γ\' Λυκείου για το μέλλον και τις σπουδές.',
    event_date: new Date(Date.now() + 21 * 86400000).toISOString().split('T')[0],
    event_time: '11:00',
    location: 'Αμφιθέατρο & Βιβλιοθήκη',
    cover_image_url: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

export const INITIAL_MOCK_IDEAS: StudentIdea[] = [
  {
    id: 'idea-1',
    school_id: 'sch-1ο-gel-athens',
    student_uid: 'uid-student-demo',
    student_name: 'Μαρία Γεωργίου',
    title: 'Εγκατάσταση νέων κάδων ανακύκλωσης σε κάθε όροφο',
    description: 'Προτείνω να τοποθετηθούν κάδοι χωριστής συλλογής χαρτιού και πλαστικού έξω από τις αίθουσες διδασκαλίας για να μειώσουμε τα σκουπίδια.',
    category: 'Περιβάλλον',
    status: 'accepted',
    admin_response: 'Εξαιρετική ιδέα! Η πρόταση εγκρίθηκε από το 15μελές και ο Διευθυντής παράγγειλε ήδη 10 νέους κάδους.',
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: 'idea-2',
    school_id: 'sch-1ο-gel-athens',
    student_uid: 'uid-student-demo',
    student_name: 'Μαρία Γεωργίου',
    title: 'Δημιουργία χαλαρωτικής μουσικής στο διάλειμμα',
    description: 'Θα ήταν πολύ ωραίο να παίζει χαμηλή μουσική από τα ηχεία του σχολείου κατά τη διάρκεια των μεγάλων διαλειμμάτων.',
    category: 'Εκδηλώσεις',
    status: 'under_review',
    admin_response: 'Το συζητάμε με τον υπεύθυνο καθηγητή για το σύστημα ηχείων.',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'idea-3',
    school_id: 'sch-1ο-gel-athens',
    student_uid: 'uid-student-nikos',
    student_name: 'Νίκος Δημητρίου',
    title: 'Αντικατάσταση των φιλέ στο γήπεδο βόλεϊ',
    description: 'Το φιλέ του βόλεϊ είναι σχισμένο. Χρειάζεται αντικατάσταση για να μπορούμε να παίζουμε στους αγώνες.',
    category: 'Αθλητισμός',
    status: 'new',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
